### ISSUE TITLE
64 Hanafuda - Tenshi no Yakusoku crashes at launch

### ISSUE THREAD

**Issue by DerekTurtleRoe** [SimoneN64/Kaizen#10]
64 Hanafuda - Tenshi no Yakusoku (J) [!] - 36D1B4EF15CDA8139FACE7E118CB34727C30BF29

This game crashes immediately to the desktop with no error messages.

Tested on the latest version of Gadolinium on Windows 10.

**Comment by SimoneN64** [comment]
Status update:
![image](https://user-images.githubusercontent.com/91993281/232353282-5daf6137-efe0-473c-b3e6-a7c0c1eb203b.png)

**Comment by DerekTurtleRoe** [comment]
@SimoneN64 Nice!

**Comment by SimoneN64** [comment]
Seems to be going in game!
