### ISSUE TITLE
Dillon's "basic" test ROM crashes the emulator

### ISSUE THREAD

**Issue by DerekTurtleRoe** [SimoneN64/Kaizen#16]
This test: https://github.com/Dillonb/n64-tests/blob/master/src/basic.asm

This crashes the emulator at launch.

Tested on the latest version of Gadolinium on Windows 10.

**Comment by SimoneN64** [comment]
Yep... This must be some dumb regression and I've actually already started to look into it recentlym It's strange because I pass most of Krom's tests and quite a few from n64-systemtest.

**Comment by DerekTurtleRoe** [comment]
> Yep... This must be some dumb regression and I've actually already started to look into it recently. It's strange because I pass most of Krom's tests and quite a few from n64-systemtest.

It also crashes several other emulators, so I wouldn't be too hard on yourself for it. 😄

**Comment by SimoneN64** [comment]
> > Yep... This must be some dumb regression and I've actually already started to look into it recently. It's strange because I pass most of Krom's tests and quite a few from n64-systemtest.
> 
> It also crashes several other emulators, so I wouldn't be too hard on yourself for it. 😄 

Heh, I used to pass it though, that's my problem with this issue 😁

**Comment by DerekTurtleRoe** [comment]
Interesting, a regression 🤔

**Comment by SimoneN64** [comment]
Can't reproduce anymore! Closing as fixed
