### ISSUE TITLE
[Feature request] Don't generate .EEPROM or .MEMPAK files unnecessarily

### ISSUE THREAD

**Issue by DerekTurtleRoe** [SimoneN64/Kaizen#59]
Currently, the way this works is that a .EEPROM and .MEMPAK file are generated for each title you launch in Gadolinium. Not all games have EEPROM or MEMPAK support, so generating these files takes up space and clutters the file system. Being able to detect if the game needs those files beforehand would be awesome 😄 

I have a database of which games support which save types if needed. 😄

**Comment by DerekTurtleRoe** [comment]
Also, I see code for FlashRAM and SRAM save support, which is good, but they should probably have their own file extension to reduce confusion and prevent things from getting overwritten.

**Comment by SimoneN64** [comment]
> Also, I see code for FlashRAM and SRAM save support, which is good, but they should probably have their own file extension to reduce confusion and prevent things from getting overwritten.
> 
> An example would be if a game supports more than one save type, and both are considered .EEPROM or .MEMPAK saves, then when you save using another method, it gets overwritten. 😅 

No I don't currently do anything with Flash or SRAM. I can just detect them I guess.

**Comment by SimoneN64** [comment]
Addressed in 8c044b5
