### ISSUE TITLE
Chameleon Twist 2 (all versions) - crash at boot

### ISSUE THREAD

**Issue by DerekTurtleRoe** [SimoneN64/Kaizen#69]
Chameleon Twist 2 (PAL) - BBCA485EE38E07DA78F44E5DE653311B8EDC18F2
Chameleon Twist 2 (NTSC) - 9FA379D66B218228DA3CBF386C91D857C677F489
Chameleon Twist 2 (NTSC-J) - 0F14F7C1E2A72008B83CBEA6A79BA38B8971561E

This game crashes at boot.

Tested on the latest version of Gadolinium on Windows 10.

**Comment by SimoneN64** [comment]
Latest dev gets in-game
