### ISSUE TITLE
Christmas Flame Demo by Halley's Comet Software (PD) - hangs at intro

### ISSUE THREAD

**Issue by DerekTurtleRoe** [SimoneN64/Kaizen#74]
Christmas Flame Demo by Halley's Comet Software (PD) - 1B6281035B6C4CBA78FADFECC0ACFBEAEA73F879

This homebrew hangs at the intro.

Tested on the latest version of Gadolinium on Windows 10.

**Comment by SimoneN64** [comment]
Interestingly, I think many of these "(PD)" (which I don't know what it means) titles crash or hang on a black screen

**Comment by DerekTurtleRoe** [comment]
> Interestingly, I think many of these "(PD)" (which I don't know what it means) titles crash or hang on a black screen

PD here stands for "public domain". They are mostly homebrew and demoscene releases, so they are usually a good test of basic functionality, and occasionally they do clever tricks and can test certain edge cases in emulation.

**Comment by DerekTurtleRoe** [comment]
Also, worth noting is that I'm only opening issues for the ones that don't boot or don't function properly, most of them run perfectly well at first boot 😄

**Comment by SimoneN64** [comment]
Works on latest dev.
