### ISSUE TITLE
Conker's Bad Fur Day (U) - hangs at boot

### ISSUE THREAD

**Issue by DerekTurtleRoe** [SimoneN64/Kaizen#79]
Conker's Bad Fur Day (U) - 4CBADD3C4E0729DEC46AF64AD018050EADA4F47A

This game hangs at boot.

Interestingly, the PAL version boots and even goes into the menus and in-game.

Tested on the latest version of Gadolinium on Windows 10.

**Comment by SimoneN64** [comment]
It just takes a long time. Some games just be like this, I don't know why. Just tested that it goes in game
