### ISSUE TITLE
2 Blokes and an Armchair homebrew causes a crash with no error messages

### ISSUE THREAD

**Issue by DerekTurtleRoe** [SimoneN64/Kaizen#9]
'2 Blokes & An Armchair - N64 Remix Remix by Tesko (PD).z64' - DBCAC7AC8105089597C94153F8B0A10E6B25B61E

This homebrew causes the emulator to crash to the desktop with no error messages or notice at all.

Testing was done on the latest version of Gadolinium on Windows 10.

**Comment by SimoneN64** [comment]
Thanks! Have you tried running it from the terminal and see if you get any messages? The best case scenario is a fatal log from my emulator from something unimplemented. If there are no messages in the terminal either, then that's even worse 😅 It means it's likely to straight up be a segfault...

**Comment by DerekTurtleRoe** [comment]
> Thanks! Have you tried running it from the terminal and see if you get any messages? The best case scenario is a fatal log from my emulator from something unimplemented. If there are no messages in the terminal either, then that's even worse 😅 It means it's likely to straight up be a segfault...

Unfortunately when I did it just did the same thing. 😖

**Comment by SimoneN64** [comment]
Ok cool. Tomorrow I'll repro and keep you updated. Hopefully also can fix the bug 🤞 Thanks

**Comment by SimoneN64** [comment]
Latest dev works
