### ISSUE TITLE
Duck Dodgers Starring Daffy Duck (U) - hangs at intro

### ISSUE THREAD

**Issue by DerekTurtleRoe** [SimoneN64/Kaizen#99]
Duck Dodgers Starring Daffy Duck (U) - 2C840E2991D6A2AF63C4EFE830240FC49D93FC9A

This game hangs at the intro.

Tested on the latest version of Windows 10.

**Comment by SimoneN64** [comment]
I was able to play through the entire intro and in-game with the latest dev
